version: 3
workdir: .
allow:
  depOnAnyVendor: false
excludeFiles:
  - "^.*_test\\.go$"

vendors:
  go-common:
    in:
      - golang.org/x/sync/errgroup
      - github.com/stretchr/testify/**
  3rd-cobra: { in: github.com/spf13/cobra }

commonVendors:
  - go-common

components:
  main: { in: cmd/*/ }
  commands: { in: cmd/*/internal/commands }
  lib: { in: cmd/*/internal/**/lib/** }

deps:
  main:
    mayDependOn:
      - commands
  commands:
    mayDependOn:
      - lib
    canUse:
      - 3rd-cobra
